// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: egg.proto

package note_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EggNutritionClient is the client API for EggNutrition service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EggNutritionClient interface {
	AddEntry(ctx context.Context, in *AddMealRequest, opts ...grpc.CallOption) (*AddMealResponse, error)
	RemoveEntry(ctx context.Context, in *RemoveMealRequest, opts ...grpc.CallOption) (*RemoveMealResponse, error)
	GetEntry(ctx context.Context, in *GetMealRequest, opts ...grpc.CallOption) (*GetMealResponse, error)
	GetList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetListResponse, error)
	UpdateEntry(ctx context.Context, in *UpdateMealRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type eggNutritionClient struct {
	cc grpc.ClientConnInterface
}

func NewEggNutritionClient(cc grpc.ClientConnInterface) EggNutritionClient {
	return &eggNutritionClient{cc}
}

func (c *eggNutritionClient) AddEntry(ctx context.Context, in *AddMealRequest, opts ...grpc.CallOption) (*AddMealResponse, error) {
	out := new(AddMealResponse)
	err := c.cc.Invoke(ctx, "/EggNutrition/AddEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eggNutritionClient) RemoveEntry(ctx context.Context, in *RemoveMealRequest, opts ...grpc.CallOption) (*RemoveMealResponse, error) {
	out := new(RemoveMealResponse)
	err := c.cc.Invoke(ctx, "/EggNutrition/RemoveEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eggNutritionClient) GetEntry(ctx context.Context, in *GetMealRequest, opts ...grpc.CallOption) (*GetMealResponse, error) {
	out := new(GetMealResponse)
	err := c.cc.Invoke(ctx, "/EggNutrition/GetEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eggNutritionClient) GetList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetListResponse, error) {
	out := new(GetListResponse)
	err := c.cc.Invoke(ctx, "/EggNutrition/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eggNutritionClient) UpdateEntry(ctx context.Context, in *UpdateMealRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/EggNutrition/UpdateEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EggNutritionServer is the server API for EggNutrition service.
// All implementations must embed UnimplementedEggNutritionServer
// for forward compatibility
type EggNutritionServer interface {
	AddEntry(context.Context, *AddMealRequest) (*AddMealResponse, error)
	RemoveEntry(context.Context, *RemoveMealRequest) (*RemoveMealResponse, error)
	GetEntry(context.Context, *GetMealRequest) (*GetMealResponse, error)
	GetList(context.Context, *emptypb.Empty) (*GetListResponse, error)
	UpdateEntry(context.Context, *UpdateMealRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedEggNutritionServer()
}

// UnimplementedEggNutritionServer must be embedded to have forward compatible implementations.
type UnimplementedEggNutritionServer struct {
}

func (UnimplementedEggNutritionServer) AddEntry(context.Context, *AddMealRequest) (*AddMealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEntry not implemented")
}
func (UnimplementedEggNutritionServer) RemoveEntry(context.Context, *RemoveMealRequest) (*RemoveMealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveEntry not implemented")
}
func (UnimplementedEggNutritionServer) GetEntry(context.Context, *GetMealRequest) (*GetMealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntry not implemented")
}
func (UnimplementedEggNutritionServer) GetList(context.Context, *emptypb.Empty) (*GetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedEggNutritionServer) UpdateEntry(context.Context, *UpdateMealRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEntry not implemented")
}
func (UnimplementedEggNutritionServer) mustEmbedUnimplementedEggNutritionServer() {}

// UnsafeEggNutritionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EggNutritionServer will
// result in compilation errors.
type UnsafeEggNutritionServer interface {
	mustEmbedUnimplementedEggNutritionServer()
}

func RegisterEggNutritionServer(s grpc.ServiceRegistrar, srv EggNutritionServer) {
	s.RegisterService(&EggNutrition_ServiceDesc, srv)
}

func _EggNutrition_AddEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EggNutritionServer).AddEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EggNutrition/AddEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EggNutritionServer).AddEntry(ctx, req.(*AddMealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EggNutrition_RemoveEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EggNutritionServer).RemoveEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EggNutrition/RemoveEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EggNutritionServer).RemoveEntry(ctx, req.(*RemoveMealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EggNutrition_GetEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EggNutritionServer).GetEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EggNutrition/GetEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EggNutritionServer).GetEntry(ctx, req.(*GetMealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EggNutrition_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EggNutritionServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EggNutrition/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EggNutritionServer).GetList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EggNutrition_UpdateEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EggNutritionServer).UpdateEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EggNutrition/UpdateEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EggNutritionServer).UpdateEntry(ctx, req.(*UpdateMealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EggNutrition_ServiceDesc is the grpc.ServiceDesc for EggNutrition service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EggNutrition_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EggNutrition",
	HandlerType: (*EggNutritionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEntry",
			Handler:    _EggNutrition_AddEntry_Handler,
		},
		{
			MethodName: "RemoveEntry",
			Handler:    _EggNutrition_RemoveEntry_Handler,
		},
		{
			MethodName: "GetEntry",
			Handler:    _EggNutrition_GetEntry_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _EggNutrition_GetList_Handler,
		},
		{
			MethodName: "UpdateEntry",
			Handler:    _EggNutrition_UpdateEntry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "egg.proto",
}
